### ISSUE TITLE
Add physics mod support 

### ISSUE THREAD

**Issue by The-Bombastic** [sixthsurge/photon#82] opened 2023-11-18 08:34 UTC
### Description

It would be very cool to play with a physics mod and this shader.

**Comment by Patomosm** [comment] 2023-11-18 10:16
Mod support is not shader dependent. At most, a few glitches may appear.
Let us know if you have any issues with Physic Mods.

**Comment by xlifi** [comment] 2024-02-03 02:57
> Mod support is not shader dependent. At most, a few glitches may appear. Let us know if you have any issues with Physic Mods.

for physics mod it is
https://github.com/haubna/PhysicsMod?tab=readme-ov-file#shaders

**Comment by sixthsurge** [comment] 2024-04-07 08:41
duplicate of #56

**Closed by sixthsurge** 2024-04-07 08:41 UTC
Labels: enhancement
