### ISSUE TITLE
Transition from rough to smooth seems harsh

### ISSUE THREAD

**Issue by andrwcrr** [sixthsurge/photon#72] opened 2023-11-07 00:00 UTC
### What happened?

There is a clear and harsh change from a rough surface transitioning to a smooth surface with `Specular Mapping` and a PBR resource pack enabled. Expected results are a much smoother transition between rough and smooth. Here is an example of [VNR](https://github.com/Poudingue/Vanilla-Normals-Renewed)'s gold and lapis blocks:
![image](https://github.com/sixthsurge/photon/assets/128940455/f1debbd9-f072-4c02-8b12-28f9f22a29a6)

### Minecraft Version

1.20.1

### Which shader mod are you using?

Iris

### Shader mod version

1.6.10

### Shader settings

```conf
#Mon Nov 06 19:54:08 AST 2023
SPECULAR_MAPPING=true
```

**Comment by Patomosm** [comment] 2023-11-07 19:22
Can be a peculiarity of the texture pack. Photon has LabPBR (old and new) support, not autogenerated PBR ones, like Complementary Shader has.
My texture pack is not affected. **What's your?**
![Base Profile Screenshot 2023 11 07 - 20 07 59 25](https://github.com/sixthsurge/photon/assets/133518090/8c521e2c-033c-4683-8063-005053a998cb)

**Comment by andrwcrr** [comment] 2023-11-07 19:58
The resource pack I'm using is [VNR](https://github.com/Poudingue/Vanilla-Normals-Renewed). What's the name of your resource pack and where can I get it?

**Comment by Patomosm** [comment] 2023-11-07 20:17
Here it is! The description says: "... based on vanilla but with normals and **proper glossiness information**."
The previews below the description show reflections like yours, so it's just the feature of the texture-pack, not an issue.

My pack is [Here](https://patomosm-stuff.jimdosite.com/java-version/)

**Comment by andrwcrr** [comment] 2023-11-07 21:51
Can you recommend a free resource pack that does not have this issue?

**Comment by Patomosm** [comment] 2023-11-07 22:04
https://modrinth.com/resourcepack/patrix-32x/changelog?g=1.20.1

**Comment by andrwcrr** [comment] 2023-11-07 23:07
It does indeed happen with Patrix, see the 9th row of pixels from the bottom on the face of the iron block thats is facing to the right, it is just less noticeable owing to the fact that it is a higher resolution pack:

![image](https://github.com/sixthsurge/photon/assets/128940455/767f6abc-fc10-4f73-b6db-cf781c4d3bb7)

Heres what it looks like with [Bliss](https://github.com/X0nk/Bliss-Shader):

![image](https://github.com/sixthsurge/photon/assets/128940455/acbf3533-270b-40c3-920a-a320ba330ac4)

**Comment by Patomosm** [comment] 2023-11-07 23:54
It's not the same reflection appearance. I noticed that you are missing somo mods to complete some effects like continued grass.
This list for 1.20.2 version will help you:
![image](https://github.com/sixthsurge/photon/assets/133518090/341f03d3-d0bf-4e3c-b095-6e50cde147ff)

**Comment by andrwcrr** [comment] 2023-11-08 05:59
Those mods would not have any effect on the specular textures of the blocks we looked at, however I added them anyways. Here is a video showcasing the same 9th row of pixels from the bottom reflecting no light whereas the adjacent pixels do reflect light, this suggests there is some sort of cutoff value where a pixel does not reflect light in photon, which shouldn't be, it should gradually decrease. I then switch to Bliss and I show that the same row of pixels do indeed reflect (less but still some) light as they should:

https://github.com/sixthsurge/photon/assets/128940455/8e49d6e6-c6a3-4eca-92fe-4bac45e03c0b

**Comment by Patomosm** [comment] 2023-11-08 16:01
A LabPBR texture pack consists of 3 images for the same texture: 1) the base image, 2) the bump-map image, and 3) the image for the lighting and reflection effects.
In the case of the iron block, the base image represents a sheet metal with darker areas of rust, which do not reflect light in the same way as shiny light iron does; In addition, the horizontal dark lines are located right in the shadow position of the simulated bend of the sheet metal, so there is nothing strange about it.

The comparison below shows how two different shaders calculate the interaction of texture images:
**Photon on the left is more effective with highlights and reflections (flattening reliefs), while Bliss on the right is more effective with bump-maps (blurring reflections).**

![Comparazione](https://github.com/sixthsurge/photon/assets/133518090/fef29d7d-e024-4815-9a40-85fd2d3c2a0d)

I reiterate that all this is not an issue, but only programming choices.

**Comment by Patomosm** [comment] 2023-11-08 16:13
Again:
Photon is more effective with lights and reflections. **Do you understand where the soul-torch is?**

![Screenshot 2023-11-08 170833](https://github.com/sixthsurge/photon/assets/133518090/f74e3a1b-4f23-40a0-8b93-2d0e5d555043)

**Comment by Patomosm** [comment] 2023-11-08 16:32
No, because Photon is unique in its programming choices.
That's why it's my favorite.

**Comment by andrwcrr** [comment] 2023-11-08 16:54
Well they weren't the best "programming choices" in my humble opinion which is why I opened an issue. I however am glad that you agree that this is to to with the shader and not the resource pack.

**Comment by Patomosm** [comment] 2023-11-08 17:46
No, you didn't understand me.
I've explained why the effect is more noticeable in photon than in other shaders, not that photon is the only one responsible.

**Comment by andrwcrr** [comment] 2023-11-08 17:48
So this effect has to do with the shader right? And not the resource pack like you initially claimed?

**Comment by Patomosm** [comment] 2023-11-08 17:51
Look at this image: PURE VANILLA, PHOTON and NO ISSUE... understood?

![Base Profile Screenshot 2023 11 08 - 16 24 41 34](https://github.com/sixthsurge/photon/assets/133518090/74485791-3ffc-49ec-bd49-840b77abc936)

**Comment by andrwcrr** [comment] 2023-11-08 18:15
I am not trying to troll, this is a genuine concern I have, I am happy to agree to disagree if we cannot come to a conclusion. Also I don't see any reflections at all in that image so I'm assuming that isn't the default settings for photon because photon has hardcoded speculars enabled by default correct?

**Comment by Patomosm** [comment] 2023-11-08 18:51
> A LabPBR texture pack consists of 3 images for the same texture: 1) the base image, 2) the bump-map image, and 3) the image for the lighting and reflection effects. In the case of the iron block, the base image represents a sheet metal with darker areas of rust, which do not reflect light in the same way as shiny light iron does; In addition, the horizontal dark lines are located right in the shadow position of the simulated bend of the sheet metal, so there is nothing weird about it.
> 
> The comparison below shows how two different shaders calculate the interaction of texture images: **Photon on the left is more effective with highlights and reflections (flattening reliefs), while Bliss on the right is more effective with bump-maps (blurring reflections).**
> 
> ![Comparazione](https://user-images.githubusercontent.com/133518090/281464131-fef29d7d-e024-4815-9a40-85fd2d3c2a0d.png)
> 
> I reiterate that all this is not an issue, but only programming choices.

Do you really read at that post of mine?
Reflections depend on the presence of extra textures within a package, not just the shader's ability to read them!
Flat Vanilla textures doesn't have LabPBR features, so ANY SHADER won't be able to show reflections on it!
Again: it is not a bug! It is not an issue!

**Comment by tsumi7** [comment] 2023-11-08 18:55
Yes, it's a bug related to the shader, the transition from rough/smooth can be improved.

@Patomosm Photon has builtin pbr properties for certain blocks even if there is no pbr resource pack installed. Reset your shader settings, remove all resource packs and place a gold block to see this easily.

**Comment by Patomosm** [comment] 2023-11-08 18:58
There are shaders that have a feature called "Autogen. PBR" that creates generic reflections, such as Complementary Shader.
Photon has "LabPBR" mode or "SeusPBRmode".

**Comment by andrwcrr** [comment] 2023-11-08 18:58
I rest my case. Thanks tsumi

**Comment by tsumi7** [comment] 2023-11-08 19:03
Current Behavior:

https://github.com/sixthsurge/photon/assets/90137856/ddf1d43a-452b-4ff4-b63f-8bd448cb6850

Proposed fix (WIP):

https://github.com/sixthsurge/photon/assets/90137856/ed7f47b7-0f30-452c-b5f3-d7f33afdc00f

**Comment by Patomosm** [comment] 2023-11-08 19:10
You are playing with a custom texture-pack, not with original Vanilla. I'm very sure because I tried Vanilla with all the reflection option enabled in photon.
And that is the prove I'm right:
![Base Profile Screenshot 2023 11 08 - 20 01 39 65](https://github.com/sixthsurge/photon/assets/133518090/bb9e91b3-b425-4aa8-b9fe-719434531917)

**Comment by Patomosm** [comment] 2023-11-08 19:22
> I rest my case. Thanks tsumi

Rest in peace.

**Comment by Patomosm** [comment] 2023-11-08 20:04
Try this:
_ enable all "reflection" in "materials" section.
_ disable "roughness Support" in "Reflections" subsection.

**Comment by andrwcrr** [comment] 2023-11-08 20:08
If roughness support is disabled then what's the point of this issue? I want to use roughness without it transitioning harshly to smoothness, rather than not enabling roughness at all.

**Comment by Patomosm** [comment] 2023-11-08 20:32
Try my options and let me know. Roughness support is enabled.
Remember my explication about LabPBR... the third image type of a texture is the key to set roughness, reflections and emitting parts. Therefore, the custom package has the first weight to the issue. There isn't a general fix for this on shader programming, I think.

[photon-main.zip.txt](https://github.com/sixthsurge/photon/files/13301018/photon-main.zip.txt)

**Comment by Patomosm** [comment] 2023-11-08 20:37
The transition from rough to smooth can be reduced as the texture resolution increases. With smaller pixels, the gradation will be almost invisible.
My advice is to try a texture pack that is 128x or higher, at the cost of performance.

**Comment by Patomosm** [comment] 2023-11-08 20:51
Look at this picture below. The armors have higher resolution than previously metallic blocks and have no rusty effects.
Do you see any related issue? Let me know what you dislike.

![Base Profile Screenshot 2023 11 08 - 21 44 32 86](https://github.com/sixthsurge/photon/assets/133518090/3961219d-e136-4797-aa86-a85b465733b4)

**Comment by Patomosm** [comment] 2023-11-08 22:14
I finally found the option that is causing the problem: "Specular Mapping".
Maybe it can't handle textures with indexed colors, that's my theory.

![Senzanome](https://github.com/sixthsurge/photon/assets/133518090/c77f3241-d320-4473-ac5b-8d41453a781b)

**Comment by Patomosm** [comment] 2023-11-17 17:18
Calcite material made by me. At the right side, with "Specular Mapping" on, you can bare distinguish reflective pixels.
In the screenshot before, copper rusty pixels have completely no reflective green channel, appearing very scratched.

![image](https://github.com/sixthsurge/photon/assets/133518090/7c4a49fa-725f-44ec-b671-3c21899a810c)

**Comment by sixthsurge** [comment] 2024-04-07 08:30
fixed

**Closed by sixthsurge** 2024-04-07 08:30 UTC
Labels: bug
